/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.NetworkCloudGraphicalEditor=function(id,_1aa2){draw2d.GraphicalEditor.call(this,id);this.readonly=_1aa2;};draw2d.NetworkCloudGraphicalEditor.prototype=new draw2d.GraphicalEditor();draw2d.NetworkCloudGraphicalEditor.prototype.type="draw2d.NetworkCloudGraphicalEditor";draw2d.NetworkCloudGraphicalEditor.prototype.setModel=function(model){try{this.model=model;this.getGraphicalViewer().setModel(this.model);this.getGraphicalViewer().setEditPartFactory(new draw2d.NetworkCloudGraphicalEditorFactory(this.readonly));this.getGraphicalViewer().setViewPort("scrollarea");this.getGraphicalViewer().setPanning(true);this.getGraphicalViewer().setCurrentSelection(null);var _1aa4=new draw2d.ExternalPalette(this.getGraphicalViewer(),"object_panel");var part1=new draw2d.ServerPalettePart(model);var part2=new draw2d.StoragePalettePart(model);var part3=new draw2d.SwitchPalettePart(model);_1aa4.addPalettePart(part1);part1.setPosition(20,40);_1aa4.addPalettePart(part2);part2.setPosition(20,90);_1aa4.addPalettePart(part3);part3.setPosition(20,140);var _1aa8=new draw2d.Toolbar("toolbar");var _1aa9=new draw2d.ToolbarButtonGroup();_1aa8.addElement(_1aa9);_1aa9.addElement(new draw2d.ToolbarButtonSave(this));if(draw2d.Configuration.APPLY_XML!==null){_1aa9.addElement(new draw2d.ToolbarButtonApply(this));}_1aa9.addElement(new draw2d.ToolbarButtonShowXML(this));var _1aaa=new draw2d.ToolbarButtonGroup();_1aa8.addElement(_1aaa);_1aaa.addElement(new draw2d.ToolbarButtonUndo(this));_1aaa.addElement(new draw2d.ToolbarButtonRedo(this));this.getGraphicalViewer().addSelectionListener(new draw2d.FlowMenu(editor.getGraphicalViewer()));this.propertyPanel=new draw2d.PropertyPanel("property_panel");this.getGraphicalViewer().addSelectionListener(this.propertyPanel);}catch(e){pushErrorStack(e,"draw2d.NetworkCloudGraphicalEditor.prototype.setModel=function()");}};draw2d.NetworkCloudGraphicalEditor.prototype.getCommandStack=function(){return this.getGraphicalViewer().getCommandStack();};draw2d.NetworkCloudGraphicalEditor.prototype.setFatalError=function(_1aab){var _1aac=document.createElement("div");var _1aad=document.createElement("div");_1aad.className="fatal_error_message";_1aac.className="fatal_error_overlay";_1aad.innerHTML="<br><br><br><br><br>"+_1aab;document.body.appendChild(_1aac);document.body.appendChild(_1aad);new fx.Opacity(_1aac).setOpacity(0.3);_1aac.style.display="";};draw2d.NetworkCloudGraphicalEditor.prototype.isReadonly=function(){return this.readonly;};draw2d.NetworkCloudGraphicalEditor.prototype.getModel=function(){return this.model;};