/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.shape.uml.Actor=function(name){this.portRight=null;draw2d.VectorFigure.call(this);this.setName(name);this.setDimension(50,90);};draw2d.shape.uml.Actor.prototype=new draw2d.VectorFigure();draw2d.shape.uml.Actor.prototype.type="shape.uml.Actor";draw2d.shape.uml.Actor.prototype.setName=function(name){this.label.innerHTML=name;};draw2d.shape.uml.Actor.prototype.setWorkflow=function(_144f){draw2d.VectorFigure.prototype.setWorkflow.call(this,_144f);if(_144f!==null&&this.portRight===null){this.portRight=new draw2d.Port();this.portRight.setWorkflow(_144f);this.addPort(this.portRight,this.width,this.height/2);this.portLeft=new draw2d.Port();this.portLeft.setWorkflow(_144f);this.addPort(this.portLeft,0,this.height/2);}};draw2d.shape.uml.Actor.prototype.createHTMLElement=function(){var item=draw2d.Figure.prototype.createHTMLElement.call(this);this.label=document.createElement("div");this.label.style.width="100%";this.label.style.height="20px";this.label.style.position="absolute";this.label.style.textAlign="center";this.label.style.top="0px";this.label.style.left="0px";this.label.style.fontSize="8pt";this.disableTextSelection(this.label);return item;};draw2d.shape.uml.Actor.prototype.setDimension=function(w,h){draw2d.VectorFigure.prototype.setDimension.call(this,w,h);if(this.portRight!==null){this.portRight.setPosition(this.width,this.height/2);this.portLeft.setPosition(0,this.height/2);}};draw2d.shape.uml.Actor.prototype.paint=function(){draw2d.VectorFigure.prototype.paint.call(this);var _1453=this.getWidth()/2;var _1454=this.getWidth()/4;var _1455=this.getHeight()/2;var _1456=parseInt(this.label.style.height);var _1457=this.getWidth()*0.2;var _1458=this.getHeight()*0.1;this.graphics.drawOval(_1453-_1457/2,0,_1457,_1458);this.graphics.drawLine(_1453,_1458,_1453,_1455);this.graphics.drawLine(_1454,_1458*2,this.getWidth()-_1454,_1458*2);this.graphics.drawLine(_1453,_1455,_1454,this.getHeight()-_1456);this.graphics.drawLine(_1453,_1455,this.getWidth()-_1454,this.getHeight()-_1456);this.graphics.paint();this.label.style.top=(this.getHeight()-_1456)+"px";this.html.appendChild(this.label);};