/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.CommandDelete=function(_a66){draw2d.Command.call(this,"delete figure");this.parent=_a66.parent;this.figure=_a66;this.workflow=_a66.workflow;this.connections=null;this.compartmentDeleteCommands=null;};draw2d.CommandDelete.prototype=new draw2d.Command();draw2d.CommandDelete.prototype.type="draw2d.CommandDelete";draw2d.CommandDelete.prototype.execute=function(){this.redo();};draw2d.CommandDelete.prototype.undo=function(){if(this.figure instanceof draw2d.CompartmentFigure){for(var i=0;i<this.compartmentDeleteCommands.getSize();i++){var _a68=this.compartmentDeleteCommands.get(i);this.figure.addChild(_a68.figure);this.workflow.getCommandStack().undo();}}this.workflow.addFigure(this.figure);if(this.figure instanceof draw2d.Connection){this.figure.reconnect();}this.workflow.setCurrentSelection(this.figure);if(this.parent!==null){this.parent.addChild(this.figure);}for(var i=0;i<this.connections.getSize();++i){this.workflow.addFigure(this.connections.get(i));this.connections.get(i).reconnect();}};draw2d.CommandDelete.prototype.redo=function(){if(this.figure instanceof draw2d.CompartmentFigure){if(this.compartmentDeleteCommands===null){this.compartmentDeleteCommands=new draw2d.ArrayList();var _a69=this.figure.getChildren().clone();for(var i=0;i<_a69.getSize();i++){var _a6b=_a69.get(i);this.figure.removeChild(_a6b);var _a6c=new draw2d.CommandDelete(_a6b);this.compartmentDeleteCommands.add(_a6c);this.workflow.getCommandStack().execute(_a6c);}}else{for(var i=0;i<this.compartmentDeleteCommands.getSize();i++){this.workflow.redo();}}}this.workflow.removeFigure(this.figure);this.workflow.setCurrentSelection(null);if(this.figure instanceof draw2d.Node&&this.connections===null){this.connections=new draw2d.ArrayList();var _a6d=this.figure.getPorts();for(var i=0;i<_a6d.getSize();i++){var port=_a6d.get(i);for(var c=0,c_size=port.getConnections().getSize();c<c_size;c++){if(!this.connections.contains(port.getConnections().get(c))){this.connections.add(port.getConnections().get(c));}}}}if(this.connections===null){this.connections=new draw2d.ArrayList();}if(this.parent!==null){this.parent.removeChild(this.figure);}for(var i=0;i<this.connections.getSize();++i){this.workflow.removeFigure(this.connections.get(i));}};