/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.CommandStack=function(){this.undostack=[];this.redostack=[];this.maxundo=50;this.eventListeners=new draw2d.ArrayList();};draw2d.CommandStack.PRE_EXECUTE=1;draw2d.CommandStack.PRE_REDO=2;draw2d.CommandStack.PRE_UNDO=4;draw2d.CommandStack.POST_EXECUTE=8;draw2d.CommandStack.POST_REDO=16;draw2d.CommandStack.POST_UNDO=32;draw2d.CommandStack.POST_MASK=draw2d.CommandStack.POST_EXECUTE|draw2d.CommandStack.POST_UNDO|draw2d.CommandStack.POST_REDO;draw2d.CommandStack.PRE_MASK=draw2d.CommandStack.PRE_EXECUTE|draw2d.CommandStack.PRE_UNDO|draw2d.CommandStack.PRE_REDO;draw2d.CommandStack.prototype.type="draw2d.CommandStack";draw2d.CommandStack.prototype.setUndoLimit=function(count){this.maxundo=count;};draw2d.CommandStack.prototype.markSaveLocation=function(){this.undostack=[];this.redostack=[];};draw2d.CommandStack.prototype.execute=function(_145c){if(_145c===null){return;}if(_145c.canExecute()==false){return;}this.notifyListeners(_145c,draw2d.CommandStack.PRE_EXECUTE);this.undostack.push(_145c);_145c.execute();this.redostack=[];if(this.undostack.length>this.maxundo){this.undostack=this.undostack.slice(this.undostack.length-this.maxundo);}this.notifyListeners(_145c,draw2d.CommandStack.POST_EXECUTE);};draw2d.CommandStack.prototype.undo=function(){var _145d=this.undostack.pop();if(_145d){this.notifyListeners(_145d,draw2d.CommandStack.PRE_UNDO);this.redostack.push(_145d);_145d.undo();this.notifyListeners(_145d,draw2d.CommandStack.POST_UNDO);}};draw2d.CommandStack.prototype.redo=function(){var _145e=this.redostack.pop();if(_145e){this.notifyListeners(_145e,draw2d.CommandStack.PRE_REDO);this.undostack.push(_145e);_145e.redo();this.notifyListeners(_145e,draw2d.CommandStack.POST_REDO);}};draw2d.CommandStack.prototype.getRedoLabel=function(){if(this.redostack.lenght===0){return "";}var _145f=this.redostack[this.redostack.length-1];if(_145f){return _145f.getLabel();}return "";};draw2d.CommandStack.prototype.getUndoLabel=function(){if(this.undostack.lenght===0){return "";}var _1460=this.undostack[this.undostack.length-1];if(_1460){return _1460.getLabel();}return "";};draw2d.CommandStack.prototype.canRedo=function(){return this.redostack.length>0;};draw2d.CommandStack.prototype.canUndo=function(){return this.undostack.length>0;};draw2d.CommandStack.prototype.addCommandStackEventListener=function(_1461){if(_1461 instanceof draw2d.CommandStackEventListener){this.eventListeners.add(_1461);}else{throw "Object doesn't implement required callback interface [draw2d.CommandStackListener]";}};draw2d.CommandStack.prototype.removeCommandStackEventListener=function(_1462){this.eventListeners.remove(_1462);};draw2d.CommandStack.prototype.notifyListeners=function(_1463,state){var event=new draw2d.CommandStackEvent(_1463,state);var size=this.eventListeners.getSize();for(var i=0;i<size;i++){this.eventListeners.get(i).stackChanged(event);}};