/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.CompartmentFigure=function(){draw2d.Node.call(this);this.children=new draw2d.ArrayList();this.setBorder(new draw2d.LineBorder(1));this.dropable=new draw2d.DropTarget(this.html);this.dropable.node=this;this.dropable.addEventListener("figureenter",function(_30){_30.target.node.onFigureEnter(_30.relatedTarget.node);});this.dropable.addEventListener("figureleave",function(_31){_31.target.node.onFigureLeave(_31.relatedTarget.node);});this.dropable.addEventListener("figuredrop",function(_32){_32.target.node.onFigureDrop(_32.relatedTarget.node);});};draw2d.CompartmentFigure.prototype=new draw2d.Node();draw2d.CompartmentFigure.prototype.type="draw2d.CompartmentFigure";draw2d.CompartmentFigure.prototype.onFigureEnter=function(_33){};draw2d.CompartmentFigure.prototype.onFigureLeave=function(_34){};draw2d.CompartmentFigure.prototype.onFigureDrop=function(_35){};draw2d.CompartmentFigure.prototype.getChildren=function(){return this.children;};draw2d.CompartmentFigure.prototype.addChild=function(_36){_36.setZOrder(this.getZOrder()+1);_36.setParent(this);this.children.add(_36);};draw2d.CompartmentFigure.prototype.removeChild=function(_37){_37.setParent(null);this.children.remove(_37);};draw2d.CompartmentFigure.prototype.setZOrder=function(_38){draw2d.Node.prototype.setZOrder.call(this,_38);for(var i=0;i<this.children.getSize();i++){this.children.get(i).setZOrder(_38+1);}};draw2d.CompartmentFigure.prototype.setPosition=function(_3a,_3b){var _3c=this.getX();var _3d=this.getY();draw2d.Node.prototype.setPosition.call(this,_3a,_3b);for(var i=0;i<this.children.getSize();i++){var _3f=this.children.get(i);_3f.setPosition(_3f.getX()+this.getX()-_3c,_3f.getY()+this.getY()-_3d);}};draw2d.CompartmentFigure.prototype.onDrag=function(){var _40=this.getX();var _41=this.getY();draw2d.Node.prototype.onDrag.call(this);for(var i=0;i<this.children.getSize();i++){var _43=this.children.get(i);_43.setPosition(_43.getX()+this.getX()-_40,_43.getY()+this.getY()-_41);}};