/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.GraphicalViewer=function(id){try{draw2d.Workflow.call(this,id);this.factory=null;this.model=null;this.initDone=false;}catch(e){pushErrorStack(e,"draw2d.GraphicalViewer=function(/*:String*/ id)");}};draw2d.GraphicalViewer.prototype=new draw2d.Workflow();draw2d.GraphicalViewer.prototype.type="draw2d.GraphicalViewer";draw2d.GraphicalViewer.prototype.setEditPartFactory=function(_91c){this.factory=_91c;this.checkInit();};draw2d.GraphicalViewer.prototype.setModel=function(_91d){try{if(_91d instanceof draw2d.AbstractObjectModel){this.model=_91d;this.checkInit();this.model.addPropertyChangeListener(this);}else{alert("Invalid model class type:"+_91d.type);}}catch(e){pushErrorStack(e,"draw2d.GraphicalViewer.prototype.setModel=function(/*:draw2d.AbstractObjectModel*/ model )");}};draw2d.GraphicalViewer.prototype.propertyChange=function(_91e){switch(_91e.property){case draw2d.AbstractObjectModel.EVENT_ELEMENT_REMOVED:var _91f=this.getFigure(_91e.oldValue.getId());this.removeFigure(_91f);break;case draw2d.AbstractObjectModel.EVENT_ELEMENT_ADDED:var _91f=this.factory.createEditPart(_91e.newValue);_91f.setId(_91e.newValue.getId());this.addFigure(_91f);this.setCurrentSelection(_91f);break;}};draw2d.GraphicalViewer.prototype.checkInit=function(){if(this.factory!==null&&this.model!==null&&this.initDone==false){try{var _920=this.model.getModelChildren();var _921=_920.getSize();for(var i=0;i<_921;i++){var _923=_920.get(i);var _924=this.factory.createEditPart(_923);_924.setId(_923.getId());this.addFigure(_924);}}catch(e){pushErrorStack(e,"draw2d.GraphicalViewer.prototype.checkInit=function()[addFigures]");}try{var _925=this.getDocument().getFigures();var _921=_925.getSize();for(var i=0;i<_921;i++){var _924=_925.get(i);if(_924 instanceof draw2d.Node){this.refreshConnections(_924);}}}catch(e){pushErrorStack(e,"draw2d.GraphicalViewer.prototype.checkInit=function()[refreshConnections]");}}};draw2d.GraphicalViewer.prototype.refreshConnections=function(node){try{var _927=new draw2d.ArrayList();var _928=node.getModelSourceConnections();var _929=_928.getSize();for(var i=0;i<_929;i++){var _92b=_928.get(i);_927.add(_92b.getId());var _92c=this.getLine(_92b.getId());if(_92c===null){_92c=this.factory.createEditPart(_92b);var _92d=_92b.getSourceModel();var _92e=_92b.getTargetModel();var _92f=this.getFigure(_92d.getId());var _930=this.getFigure(_92e.getId());var _931=_92f.getOutputPort(_92b.getSourcePortName());var _932=_930.getInputPort(_92b.getTargetPortName());_92c.setTarget(_932);_92c.setSource(_931);_92c.setId(_92b.getId());this.addFigure(_92c);this.setCurrentSelection(_92c);}}var _933=node.getOutputPorts();_929=_933.getSize();for(var i=0;i<_929;i++){var _934=_933.get(i).getConnections();var _935=_934.getSize();for(var ii=0;ii<_935;ii++){var _937=_934.get(ii);if(!_927.contains(_937.getId())){this.removeFigure(_937);_927.add(_937.getId());}}}}catch(e){pushErrorStack(e,"draw2d.GraphicalViewer.prototype.refreshConnections=function(/*:draw2d.Node*/ node )");}};