/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.VectorPropertyWindow=function(){draw2d.PropertyWindow.call(this);this.setDimension(180,150);};draw2d.VectorPropertyWindow.prototype=new draw2d.PropertyWindow();draw2d.VectorPropertyWindow.prototype.type="VectorPropertyWindow";draw2d.VectorPropertyWindow.prototype.createHTMLElement=function(){var _87=draw2d.PropertyWindow.prototype.createHTMLElement.call(this);this.lineColorLabel=this.createLabel("Line Color:",15,100);_87.appendChild(this.lineColorLabel);this.fillColorLabel=this.createLabel("Fill Color:",15,120);_87.appendChild(this.fillColorLabel);this.lineColorArea=this.createLabel("&nbsp;",85,100);this.lineColorArea.style.width="50px";this.lineColorArea.style.border="1px solid gray";this.lineColorArea.hostDialog=this;this.lineColorArea.onclick=function(){this.hostDialog.showLineColorDialog();};_87.appendChild(this.lineColorArea);this.fillColorArea=this.createLabel("&nbsp;",85,120);this.fillColorArea.style.width="50px";this.fillColorArea.style.border="1px solid gray";this.fillColorArea.hostDialog=this;this.fillColorArea.onclick=function(){this.hostDialog.showFillColorDialog();};_87.appendChild(this.fillColorArea);return _87;};draw2d.VectorPropertyWindow.prototype.onSelectionChanged=function(_88){draw2d.PropertyWindow.prototype.onSelectionChanged.call(this,_88);if(_88!==null&&(typeof _88.getColor=="function")){if(_88.getColor()!==null){this.lineColorArea.style.background=_88.getColor().getHTMLStyle();}else{this.lineColorArea.style.background="transparent";}this.lineColorArea.style.cursor="pointer";this.lineColorArea.style.border="1px solid gray";this.lineColorLabel.style.color="black";}else{this.lineColorArea.style.background="transparent";this.lineColorArea.style.cursor=null;this.lineColorArea.style.border="1px solid #d0d0d0";this.lineColorLabel.style.color="#d0d0d0";}if(_88!==null&&(typeof _88.getBackgroundColor=="function")){if(_88.getBackgroundColor()!==null){this.fillColorArea.style.background=_88.getBackgroundColor().getHTMLStyle();}else{this.fillColorArea.style.background="transparent";}this.fillColorArea.style.cursor="pointer";this.fillColorArea.style.border="1px solid gray";this.fillColorLabel.style.color="black";}else{this.fillColorArea.style.background="transparent";this.fillColorArea.style.cursor=null;this.fillColorArea.style.border="1px solid #d0d0d0";this.fillColorLabel.style.color="#d0d0d0";}};draw2d.VectorPropertyWindow.prototype.showLineColorDialog=function(){if((this.getCurrentSelection()===null)||(typeof this.getCurrentSelection().getColor!="function")){return;}var _89=new draw2d.LineColorDialog(this.getCurrentSelection());_89.setColor(this.getCurrentSelection().getColor());this.workflow.showDialog(_89);};draw2d.VectorPropertyWindow.prototype.showFillColorDialog=function(){if(typeof this.getCurrentSelection().getBackgroundColor!="function"){return;}var _8a=new draw2d.BackgroundColorDialog(this.getCurrentSelection());_8a.setColor(this.getCurrentSelection().getBackgroundColor());this.workflow.showDialog(_8a);};