/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.ModelXMLSerializer=function(){alert("do not init this class. Use the static methods instead");};draw2d.ModelXMLSerializer.toXML=function(obj,_10b7,_10b8){if(obj===undefined){return "";}if(_10b7===undefined){_10b7=obj.tag;}_10b8=_10b8?_10b8:"";var _10b9=_10b8+"   ";var t=draw2d.ModelXMLSerializer.getTypeName(obj);var _10bb="";var _10bc="";var _10bd=false;var _10be=true;switch(t){case "int":case "number":case "boolean":_10bb=obj;_10be=false;break;case "string":_10bb=draw2d.ModelXMLSerializer.xmlEncode(obj);_10be=false;break;case "date":_10bb=obj.toLocaleString();_10be=false;break;case "Array":case "array":_10bd=true;_10bb="";for(var i=0;i<obj.length;i++){var _10c0=obj[i];if(_10c0===undefined){continue;}_10bb+=draw2d.ModelXMLSerializer.toXML(_10c0,_10c0.tag,_10b9);_10be=false;}_10bb+=_10b8;break;default:if(obj!==null){var _10c1=obj.getPersistentAttributes();var _10c2=_10c1.attributes;var _10c3=_10c1;for(var name in _10c3){if(name==="attributes"||name===undefined){continue;}_10be=false;_10bb+=draw2d.ModelXMLSerializer.toXML(_10c3[name],name,_10b9);}_10bb+="\n"+_10b8;for(var name in _10c2){var _10c5=_10c2[name];if(_10c5===undefined){continue;}if(_10c5===null){_10c5="";}_10bc=_10bc+" "+name+"="+"\""+draw2d.ModelXMLSerializer.xmlEncode(_10c5)+"\"";}if(_10bc.length>0){_10bc+=" ";}}break;}if(_10bd){return _10bb;}var s="";if(_10be){s="\n"+_10b8+"<"+_10b7+_10bc+"/>";}else{s="\n"+_10b8+"<"+_10b7+_10bc+">";s+=_10bb;s+="</"+_10b7+">";}return s;};draw2d.ModelXMLSerializer.isSimpleVar=function(t){switch(t){case "int":case "string":case "String":case "Number":case "number":case "Boolean":case "boolean":case "bool":case "dateTime":case "Date":case "date":case "float":return true;}return false;};draw2d.ModelXMLSerializer.getTypeName=function(obj){if(obj===null){return "undefined";}if(obj instanceof Array){return "Array";}if(obj instanceof Date){return "Date";}var t=typeof (obj);if(t==="number"){return (parseInt(obj,10).toString()==obj)?"int":"number";}if(draw2d.ModelXMLSerializer.isSimpleVar(t)){return t;}return obj.type;};draw2d.ModelXMLSerializer.xmlEncode=function(_10ca){var t=typeof (_10ca);if(t=="number"){return ""+_10ca;}var _10cc=_10ca;var amp=/&/gi;var gt=/>/gi;var lt=/</gi;var quot=/"/gi;var apos=/'/gi;var _10d2="&#62;";var _10d3="&#38;#60;";var _10d4="&#38;#38;";var _10d5="&#34;";var _10d6="&#39;";_10cc=_10cc.replace(amp,_10d4);_10cc=_10cc.replace(quot,_10d5);_10cc=_10cc.replace(lt,_10d3);_10cc=_10cc.replace(gt,_10d2);_10cc=_10cc.replace(apos,_10d6);return _10cc;};