/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

draw2d.AddImageDialog=function(id,_d7d){draw2d.FormDialog.call(this,id);if(!(_d7d instanceof draw2d.ServerModel)){throw "Wrong type of parameter in draw2d.AddImageDialog=function(/*:String*/ id, /*:ServerModel*/ server)";}this.server=_d7d;this.currentSelectedIcon=null;this.currentSelectedImage=null;$("dialog_select_image_header").update(draw2d.I18N.DIALOG_ADDIMAGE_HEADER);this.dialog_box.select(".draw2d_window_button_ok")[0].update(draw2d.I18N.DIALOG_ADDIMAGE_OK);this.dialog_box.select(".draw2d_window_button_cancel")[0].update(draw2d.I18N.DIALOG_ADDIMAGE_CANCEL);var _d7e=$("dialog_select_image_images");_d7e.innerHTML="";var ul=$(document.createElement("ul"));ul.className="gallery";_d7e.appendChild(ul);for(var i=0;i<draw2d.ImageTemplates.length;i++){var _d81=draw2d.ImageTemplates[i];var li=$(document.createElement("li"));li.addClassName("gallery_li");li.observe("click",function(li,_d84){if(this.currentSelectedIcon!=null){this.currentSelectedIcon.removeClassName("gallery_li_selected");}this.currentSelectedIcon=li;this.currentSelectedImage=_d84;this.currentSelectedIcon.addClassName("gallery_li_selected");}.bind(this,li,_d81));var img=$(document.createElement("img"));img.addClassName("gallery_li_img");img.title=_d81.name;li.appendChild(img);if(_d81.icon!==undefined&&_d81.icon!==null){img.src=_d81.icon;}else{img.src=draw2d.Configuration.IMAGEPATH+"image_default.png";var _d86=new Element("div");_d86.update(_d81.name);li.appendChild(_d86);img.style.height="70px";img.style.width="100px";}ul.appendChild(li);}};draw2d.AddImageDialog.prototype=new draw2d.FormDialog();draw2d.AddImageDialog.prototype.type="draw2d.AddImageDialog";draw2d.AddImageDialog.prototype.onOk=function(){try{var _d87=new draw2d.ImageModel();_d87.setName(this.currentSelectedImage.name);_d87.setFileName(this.currentSelectedImage["file-name"]);_d87.setImageType(this.currentSelectedImage["image-type"]);_d87.setWriteback(this.currentSelectedImage["writeback"]);_d87.setReadonly(this.currentSelectedImage["readonly"]);var _d88=new draw2d.CommandAddImage(editor.getGraphicalViewer(),this.server,_d87);editor.getCommandStack().execute(_d88);}catch(e){alert(e);}};draw2d.AddImageDialog.prototype.onCancel=function(){};