/**
This notice must be untouched at all times.
This is the COMPRESSED version of Draw2D
WebSite: http://www.draw2d.org
Copyright: 2006 Andreas Herz. All rights reserved.
Created: 5.11.2006 by Andreas Herz (Web: http://www.freegroup.de )
LICENSE: LGPL
**/

function ellipsis(e){var w=e.getWidth()-10;var t=e.innerHTML;var _4b6=t.replace(/<br>/g,"");var _4b7=false;e.innerHTML="<span>"+t+"</span>";e=e.down();var cut=0;while(t.length>0&&e.getWidth()>=w){var _4b9=(t.length-cut/2);text="..."+t.substr(cut,t.length-1);e.innerHTML=text;_4b7=true;cut+=1;}if(_4b7){e.setAttribute("title",_4b6);}}draw2d.IdGenerator=function(){alert("Don't create an instance of this class. Call draw2d.IdGenerator.getNext()");};draw2d.IdGenerator.nextId=0;draw2d.IdGenerator.getNext=function(){draw2d.IdGenerator.nextId+=1;return draw2d.IdGenerator.nextId-1;};draw2d.IdGenerator.reserve=function(id){id=parseInt(id,10);if(isNaN(id)){id=0;}draw2d.IdGenerator.nextId=Math.max(draw2d.IdGenerator.nextId,id+1);};function urlParam(_4bb){_4bb=_4bb.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var _4bc="[\\?&]"+_4bb+"=([^&#]*)";var _4bd=new RegExp(_4bc);var _4be=_4bd.exec(window.location.href);if(_4be===null){return "";}return _4be[1];}function loadDocument(_4bf){var req=new Ajax.Request(draw2d.Configuration.GET_XML+"?xml="+_4bf,{method:"get",onFailure:function(_4c1){editor=new draw2d.NetworkCloudGraphicalEditor("paintarea",true);editor.setModel(new draw2d.VirtualNetworkCloudModel());editor.setFatalError(draw2d.I18N.ERRORMESSAGE_WRONG_MODELURL+draw2d.Configuration.GET_XML+"?xml="+_4bf);resize();},onSuccess:function(_4c2){try{var _4c3=null;var _4c4=null;if(_4c2.responseText.indexOf("<vnetwork")!==-1){_4c3=draw2d.ModelXMLDeserializer.fromXML(_4c2.responseXML.firstChild);}if(_4c3===null){_4c3=new draw2d.VirtualNetworkCloudModel();_4c4=draw2d.I18N.ERRORMESSAGE_NULL_MODEL;}editor=new draw2d.NetworkCloudGraphicalEditor("paintarea",false);editor.setModel(_4c3);if(_4c4!=null){editor.setFatalError(_4c4);}resize();}catch(e){alert("Edit Document\n"+e+"\n"+_errorStack_+"\n");}}});}function TransparentMessage(msg){this.msg=msg;}TransparentMessage.prototype.show=function(){var _4c6=$("body");this.center=document.createElement("center");this.center.id="transparentMessage";this.center.style.padding="20px";this.center.style.position="absolute";this.center.style.top="0px";this.center.style.width="100%";this.center.style.opacity="0.001";this.center.style.filter="alpha(opacity=1)";var _4c7=document.createElement("div");this.center.appendChild(_4c7);_4c7.innerHTML=this.msg;_4c7.className="transparent_message";_4c7.style.backgroundColor="#8CC73F";_4c7.style.color="white";_4c7.style.width="300px";_4c7.style.fontWeight="bold";_4c7.style.fontSize="15pt";_4c7.style.position="relative";_4c6.appendChild(this.center);var x=new fx.Opacity("transparentMessage",{duration:300}).custom(0.001,0.8);var y=new fx.Interval(function(){try{var z1=new fx.Opacity("transparentMessage",{duration:1000}).custom(0.8,0);var z2=new fx.Top("transparentMessage",{duration:1500,onComplete:function(){$("transparentMessage").remove();}}).custom(0,-100);}catch(e){alert(e);}},1);};